services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn my_first_flask_project:app
    envVars:
      - key: FLASK_ENV
        value: production